### ISSUE TITLE
Wizzy failure with Grafana 6.X

### ISSUE THREAD

**Issue by VRevol** [grafana-wizzy/wizzy#140]
Hi, we are using wizzy to import dashboards and datasources to version them in GitLab.

It is working fine using user/password in wizzy conf with grafana 5.1.0

We have now dockerized Grafana 6.1.3 and I got this erro with the corrct configuration:

```
:~/grafana$ wizzy show datasources
/usr/lib/node_modules/wizzy/src/remote/grafana.js:420
                output += 'Grafana API response status code = ' + response.statusCode;
                                                                           ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.printResponse [as _callback] (/usr/lib/node_modules/wizzy/src/remote/grafana.js:420:62)
    at self.callback (/usr/lib/node_modules/wizzy/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/lib/node_modules/wizzy/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
```
```
:~/grafana$ wizzy list dashboards
/usr/lib/node_modules/wizzy/src/remote/grafana.js:284
                                output += 'Grafana API response status code = ' + response.statusCode;
                                                                                           ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.saveHandler [as _callback] (/usr/lib/node_modules/wizzy/src/remote/grafana.js:284:66)
    at self.callback (/usr/lib/node_modules/wizzy/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/lib/node_modules/wizzy/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
```

Is it related with new Grafana version ?
Thanks for your help

**Comment by Sytten** [comment]
I got this bug this morning, it happens because an error happened and the response is undefined. I fixed it in https://github.com/grafana-wizzy/wizzy/commit/35c231fd0e93924b2b4a78dda648d283af086508

**Comment by Sytten** [comment]
Closing as fixed until we have further details from the author

**Comment by Tikam02** [comment]
Same error
