### ISSUE TITLE
 Can't generate a gif image of Grafana dashbords

### ISSUE THREAD

**Issue by karlie93** [grafana-wizzy/wizzy#172]
I want to create a dashboard list ,when i enter 'wizzy create dash-list my-first-list' ,
TypeError:
C:\Users\Geek\AppData\Roaming\npm\node_modules\wizzy\src\local\dashlist.js:150
  this.dashlistConf.use('file', { file: dashListFile });
                    ^

TypeError: Cannot read property 'use' of undefined
    at DashList.saveDashListConf (C:\Users\Geek\AppData\Roaming\npm\node_modules\wizzy\src\local\dashlist.js:150:21)
    at DashList.createIfNotExists (C:\Users\Geek\AppData\Roaming\npm\node_modules\wizzy\src\local\dashlist.js:20:10)
    at DashList.createList (C:\Users\Geek\AppData\Roaming\npm\node_modules\wizzy\src\local\dashlist.js:27:8)
    at Commands.instructions (C:\Users\Geek\AppData\Roaming\npm\node_modules\wizzy\src\commands.js:75:18)
    at Command.listener (C:\Users\Geek\AppData\Roaming\npm\node_modules\wizzy\node_modules\commander\index.js:300:8)
    at Command.emit (events.js:210:5)
    at Command.EventEmitter.emit (domain.js:475:20)
    at Command.parseArgs (C:\Users\Geek\AppData\Roaming\npm\node_modules\wizzy\node_modules\commander\index.js:637:12)
    at Command.parse (C:\Users\Geek\AppData\Roaming\npm\node_modules\wizzy\node_modules\commander\index.js:457:21)
    at Object.<anonymous> (C:\Users\Geek\AppData\Roaming\npm\node_modules\wizzy\src\index.js:13:9)

**Comment by Sytten** [comment]
Thanks for submitting, I know the gif are broken currently but its a low priority feature
