### ISSUE TITLE
can't even run 

### ISSUE THREAD

**Issue by a5a5a9** [grafana-wizzy/wizzy#182]
wizzy version
/home/roger.nvm/versions/node/v6.17.1/lib/node_modules/wizzy/src/remote/grafana/clipSrv.js:25
  );
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/roger/.nvm/versions/node/v6.17.1/lib/node_modules/wizzy/src/remote/grafana.js:5:17)

**Comment by Sytten** [comment]
Old version of node
